esphome:
  name: scarlett-cat-1
  friendly_name: Scarlett Cat 1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

external_components:
  - source:
      type: git
      url: https://github.com/Anarph/esp-home
      ref: main
    components: [ scarlett_cat ]



# Enable Home Assistant API
api:
  encryption:
    key: "2ktlcJyeqK9CN4Q0wzzfiBlOMlAKp/q1neuzEXB4iy4="

ota:
  - platform: esphome
    password: "60ce373baa42ce66b26305cd9952de24"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Scarlett-Cat-1 Fallback Hotspot"
    password: "y0EVsStu9fWR"

captive_portal:


binary_sensor:
  - platform: custom
    lambda: |-
      auto sensor = new IRLevelSensor(17, 18);
      App.register_component(sensor);
      return {sensor->binary_sensor};
    binary_sensors:
      name: "Contenant Vide"