esphome:
  name: SC1
  friendly_name: Scarlett Cat 1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Logs série et HA
logger:

# OTA pour mise à jour
ota:
  password: "ton_mdp_ota"

# API Home Assistant
api:
  encryption:
    key: "CLE_API_GENEREE_PAR_HA" # à copier/coller depuis Home Assistant
  services:
    - service: give_food
      variables:
        doses: int
      then:
        - lambda: |-
            id(scarlett_cat_component).on_give_food(doses);

    - service: take_photo
      then:
        - lambda: |-
            id(scarlett_cat_component).on_take_photo();

# WiFi
wifi:
  ssid: "Bbox-AB57F6F8"
  password: "HfcWKp9fcWEQbFFxva"

  ap:  # fallback hotspot
    ssid: "ScarlettCat Fallback"
    password: "12345678"

captive_portal:

# Téléverse ton composant depuis GitHub
external_components:
  - source: github://TON_GITHUB/esphome-scarlett-cat
    components: [ scarlett_cat ]

# Déclaration de ton composant
scarlett_cat:
  id: scarlett_cat_component

# Binaire : état de connexion du device
binary_sensor:
  - platform: status
    name: "Scarlett Cat Status"

# (Optionnel) Stocker la photo la plus récente
# Elle pourra être affichée dans Lovelace avec "picture-entity"
image:
  - platform: snapshot
    name: "Scarlett Cat Photo"
    id: scarlett_cat_photo
